Weekly Progress Update
Pseudo-Lab/data-scientist-with-python pull request #10
Opened 2024-01-06 07:33 UTC by sangwoolee392

- 학습 상태 업데이트 했습니다.

2024-01-07 04:33 UTC, wooksong approved these changes

2024-01-09 05:46 UTC, petanerd approved these changes

2024-01-11 00:52 UTC, wooksong commented on README.md
> +| [✅](https://www.datacamp.com/completed/statement-of-accomplishment/course/73723c6abbe22d0b28800c0f8b897af01f2ba411) |  |  |  | [✅](https://app.datacamp.com/learn/courses/intermediate-python) | [✅](
```https://app.datacamp.com/learn/courses/intermediate-python```

주소가 이상합니다.

2024-01-11 00:52 UTC, wooksong requested changes
Intermediate Python Progress에 사용하신 주소 확인 부탁드려요.

2024-01-15 10:13 UTC, petanerd requested changes
잘못된 링크 : 개인 완료 링크가 아닙니다.

2024-01-15 10:13 UTC, petanerd commented on README.md
> +| [✅](https://www.datacamp.com/completed/statement-of-accomplishment/course/73723c6abbe22d0b28800c0f8b897af01f2ba411) |  | [✅](https://www.datacamp.com/completed/statement-of-accomplishment/course/f1
주소가 코스완료 링크가 아닙니다. 개인 고유링크로 변경하여 업데이트해주세요

2024-02-19 02:45 UTC, closed without merging